version: '3'
services:
  nginx:
    container_name: 'dnd-character-sheet'
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge
