#!/bin/bash
image_name=dnd-character-sheet
work_dir="$HOME/www/$image_name"
repo_dir="$HOME/repo/$image_name.git"
pre_deploy="$work_dir/pre-deploy.sh"
pre_deploy="$work_dir/post-deploy.sh"

cd $work_dir

if [ -f $pre_deploy ]; then
  $pre_deploy
fi

git --work-tree=$work_dir --git-dir=$repo_dir checkout -f

if [ -f  $post_deploy ]; then
  $post_deploy
fi
